name: Container Image CI Native
on:
  push:
    branches: [ "main" ]
    paths:
      - 'pom.xml'
      - 'src/main/java/**/*.java'
      - 'src/main/test/**/*.java'
      - 'src/main/resources/**/*.properties'
      - 'src/main/resources/**/*.yaml'
      - 'src/main/resources/**/*.xml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.1
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: upaio/helidon-chassis-microservice
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile.native
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
